stages:
  - updateDefaultBranch

update_develop_default_branch:
  stage: updateDefaultBranch
  script:
    - echo "(1/3) Pulling develop branch"
    - ssh desarrollomid "cd /home/springlabs/nestle-ceda/nestle-nestca-dashboard-front && git stash && git fetch && git checkout develop && git pull origin develop"
    - echo "(2/3) Updating dependencies"
    - ssh desarrollomid "cd /home/springlabs/nestle-ceda/nestle-nestca-dashboard-front && yarn install"
    - echo "(3/3) Building project"
    - ssh desarrollomid "cd /home/springlabs/nestle-ceda/nestle-nestca-dashboard-front && yarn build && /opt/node/bin/pm2 restart ${CI_PROJECT_NAME}"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
update_release_default_branch:
  stage: updateDefaultBranch
  script:
    - echo "(1/3) Pulling release branch"
    - ssh pruebasMID "cd /home/springlabs/nestle-ceda/nestle-nestca-dashboard-front/ && git stash && git fetch && git checkout release && git pull origin release"
    - echo "(2/3) Updating dependencies"
    - ssh pruebasMID "cd /home/springlabs/nestle-ceda/nestle-nestca-dashboard-front/ && nvm use 12 && yarn install"
    - echo "(3/3) Building project"
    - ssh pruebasMID "cd /home/springlabs/nestle-ceda/nestle-nestca-dashboard-front/ && nvm use 12 && yarn build && pm2 restart ${CI_PROJECT_NAME}"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "release"'     
